# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LOGIN_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Junk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(default='None added yet', max_length=20)),
                ('price', models.IntegerField(default=5)),
                ('avgRating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding', to='LOGIN_APP.Users')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to='LOGIN_APP.Users')),
                ('reservation', models.ManyToManyField(related_name='reserved', to='LOGIN_APP.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=180)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_review', to='LOGIN_APP.Users')),
                ('junk', models.ManyToManyField(related_name='reviewed', to='ATTIC_APP.Junk')),
                ('user', models.ManyToManyField(related_name='reviewed', to='LOGIN_APP.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('junk', models.ManyToManyField(related_name='tribe', to='ATTIC_APP.Junk')),
            ],
        ),
    ]
