# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-20 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN_APP', '0002_company'),
        ('ATTIC_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posted_junk', to='LOGIN_APP.Users'),
        ),
    ]
