# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-22 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATTIC_APP', '0006_auto_20190720_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='equipment',
            new_name='junk',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='equipment',
            new_name='junk',
        ),
        migrations.AddField(
            model_name='junk',
            name='location',
            field=models.CharField(default='None added yet', max_length=20),
        ),
    ]
