# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATTIC_APP', '0009_auto_20190722_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='junk',
            name='avgRating',
            field=models.IntegerField(default=0),
        ),
    ]
