# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATTIC_APP', '0011_auto_20190724_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='junk',
            name='image',
            field=models.ImageField(default='ATTIC_APP/images/default.jpg', upload_to='ATTIC_APP/images'),
        ),
    ]
