# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATTIC_APP', '0017_auto_20190725_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='junk',
            name='imageURL',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
