# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-20 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN_APP', '0002_company'),
        ('ATTIC_APP', '0002_equipment_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Junk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ManyToManyField(related_name='rented', to='LOGIN_APP.Users')),
                ('poster', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posted_junk', to='LOGIN_APP.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='poster',
        ),
        migrations.AlterField(
            model_name='family',
            name='equipment',
            field=models.ManyToManyField(related_name='family', to='ATTIC_APP.Junk'),
        ),
        migrations.AlterField(
            model_name='review',
            name='equipment',
            field=models.ManyToManyField(related_name='reviewed', to='ATTIC_APP.Junk'),
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
