# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-20 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN_APP', '0002_company'),
        ('ATTIC_APP', '0003_auto_20190720_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junk',
            name='customer',
        ),
        migrations.AddField(
            model_name='junk',
            name='holder',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rented', to='LOGIN_APP.Users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='junk',
            name='poster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posted_junk', to='LOGIN_APP.Users'),
        ),
    ]
