# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-20 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administrator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_administrator', to='LOGIN_APP.Users')),
                ('employee', models.ForeignKey(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_administrator', to='LOGIN_APP.Users'), on_delete=django.db.models.deletion.CASCADE, related_name='company_employee', to='LOGIN_APP.Users')),
            ],
        ),
    ]
