# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN_APP', '0003_auto_20190722_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avgRating',
            field=models.FloatField(default=0),
        ),
    ]
