# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 23:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='A person with no name apparently', max_length=20)),
                ('lname', models.CharField(default='A person with no name apparently', max_length=20)),
                ('location', models.CharField(default='None added yet', max_length=20)),
                ('username', models.CharField(default='not a required field', max_length=20)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('email', models.CharField(default='Seriously, no email? it is 2019 get with it man', max_length=80)),
                ('password', models.CharField(max_length=8)),
                ('avgRating', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_administrator', to='LOGIN_APP.Users'),
        ),
        migrations.AddField(
            model_name='company',
            name='employee',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_administrator', to='LOGIN_APP.Users'), related_name='company_employee', to='LOGIN_APP.Users'),
        ),
    ]
