# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-22 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN_APP', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.CharField(default='None added yet', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_administrator', to='LOGIN_APP.Users'),
        ),
        migrations.RemoveField(
            model_name='company',
            name='employee',
        ),
        migrations.AddField(
            model_name='company',
            name='employee',
            field=models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_administrator', to='LOGIN_APP.Users'), related_name='company_employee', to='LOGIN_APP.Users'),
        ),
    ]
