# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-20 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATTIC_APP', '0005_auto_20190720_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junk',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding', to='LOGIN_APP.Users'),
        ),
        migrations.AlterField(
            model_name='junk',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to='LOGIN_APP.Users'),
        ),
    ]
