# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-23 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN_APP', '0003_auto_20190722_1251'),
        ('ATTIC_APP', '0007_auto_20190722_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='family',
            name='junk',
        ),
        migrations.AddField(
            model_name='junk',
            name='price',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='junk',
            name='reservation',
            field=models.ManyToManyField(related_name='reserved', to='LOGIN_APP.Users'),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.AddField(
            model_name='tribe',
            name='junk',
            field=models.ManyToManyField(related_name='tribe', to='ATTIC_APP.Junk'),
        ),
    ]
