# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-23 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATTIC_APP', '0008_auto_20190722_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junk',
            name='price',
            field=models.IntegerField(default=5),
        ),
    ]
