# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATTIC_APP', '0010_junk_avgrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junk',
            name='avgRating',
            field=models.FloatField(default=0),
        ),
    ]
