# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN_APP', '0003_auto_20190722_1251'),
        ('ATTIC_APP', '0011_auto_20190724_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('junk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='ATTIC_APP.Junk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='LOGIN_APP.Users')),
            ],
        ),
    ]
